improvement/bbgv filter
sanctuarycomputer/bbgv pull request #129
Opened 2022-06-21 17:17 UTC by bbqxaxiu

- adding dropdown + dropdown styling
- adding down caret

### Description

### Type(s) of changes

- [ ] Bug fix
- [ ] New feature
- [ ] Update to an existing feature

### Motivation for PR

### How Has This Been Tested?

### Applicable screenshots:

### Follow-up PR

2022-06-23 18:26 UTC, bbqxaxiu commented on src/components/CompaniesFilter.tsx
> +            labels[1].innerHTML = CompanyFilters.ALL_SECTORS;
in an ideal world we'd just do:

labels[0].innerHTML = companyType
labels[1].innerHTML = industryType

but the reason we can't do this is because the call to the setCompanyType and setIndustryType hook isn't guaranteed to have finished executing by the time we get to having to change the labels on the dropdown

2022-06-23 18:27 UTC, bbqxaxiu commented on src/components/CompaniesFilter.tsx
> +          onClick={(e) => {
whenever the clear filter button is clicked, we need to reset the labels on the dropdown so that they say "All Company Types" and "All Sectors" again

2022-06-23 22:40 UTC, limsohee1002 reviewed
One thing that I am noticing is cursor is not change when it hover over clickable element

2022-06-23 22:40 UTC, limsohee1002 commented on src/components/CompaniesFilter.tsx
> +        <button
This button doesn't seem to have a hover cursor change. The cursor should change whenever it is clickable. Also, is there any hover state

2022-06-23 22:40 UTC, limsohee1002 commented on src/components/CompaniesFilter.tsx
> +            labels[1].innerHTML = CompanyFilters.ALL_SECTORS;
Can we use state to change the inner html?
```
  const [companyFilterButtonLabel, setCompanyFilterButtonLabel] = useState('AllCompanyTypes');
```
and on click event
``` 
(e) => {
  setCompanyFilterButtonLabel(CompanyFilters.ALL_COMPANIES)
}
```

2022-06-27 13:04 UTC, mokaymokay requested changes
It might be better to managed the filteredInvestments and filteredPortfolioCompanies state in the parent (view), and have the filters component update those lists, then pass down those values to `InvestmentList` and `PortfolioListing` to display the list of companies. that way, if the list of companies doesn't mutate, your children components won't have to re-render. IMO, PortfolioListing and InvestmentList don't need to know the filtering logic, their sole responsibility is to render UI based on the list of companies

2022-06-27 14:15 UTC, bbqxaxiu commented on cms/schemas/layouts/investmentsList.js
> +            {
the client wants and is aware that there should be set, predefined options for the company type and sectors :D ty for checking in on that @limsohee1002 and @mokaymokay

2022-06-27 14:35 UTC, bbqxaxiu commented on src/components/icons/DownCaret.tsx
> +    <div className={cx('DownCaret', className)}>
I wanted to make it so that in the future if anyone wanted to apply a class to it to change its width/height/etc, they could!  Wdyt about that?

2022-06-27 15:10 UTC, bbqxaxiu commented
> It would be better to manage the filteredInvestments and filteredPortfolioCompanies state in the parent (view), and have the filters component update those values in the parent's state, then pass down those values to `InvestmentList` and `PortfolioListing` (children components) to display the list of companies. that way, if the list of companies doesn't mutate, your children components won't have to re-render. IMO, PortfolioListing and InvestmentList don't need to know about the filtering logic, their sole responsibility is to render UI based on the list of companies. we want as many dumb components as possible to reduce the cognitive overhead in our views.

this is a fire recommendation

2022-06-27 16:01 UTC, bbqxaxiu commented on src/components/CompaniesFilter.tsx
> +            labels[1].innerHTML = CompanyFilters.ALL_SECTORS;
hi Sohee! I thought about doing this too but the issue is the [DropDown component](https://reactjsexample.com/simple-dropdown-component-for-react/) we are using doesn't seem to accept a prop that lets us manually dictate what label is being shown. (if it did, we could easily pass in the current state, like you suggested.)

do you have any other suggestions/workarounds?

2022-06-27 17:10 UTC, limsohee1002 commented on src/components/CompaniesFilter.tsx
> +            options={CompanyFilters.COMPANIES}
about this comment: https://github.com/sanctuarycomputer/bbgv/pull/129/files#r905563366
can you just update the label here?

2022-06-27 17:10 UTC, limsohee1002 commented on src/components/CompaniesFilter.tsx
> +            options={CompanyFilters.SECTORS}
about this comment: https://github.com/sanctuarycomputer/bbgv/pull/129/files#r905563366
can you just update the label here?

2022-06-27 17:28 UTC, bbqxaxiu commented on src/components/CompaniesFilter.tsx
> +        <button
there's no hover state in our designs, but I'll make it so that there's a hover cursor change!

2022-06-27 17:34 UTC, bbqxaxiu commented on src/lib/cms/types.ts
> +    companyType: t.string,
hi Kay, I tried doing that but it doesn't work; this is the error I receive. I think this is because the types defined in `types.ts` of the CMS folder need to be atomic types (like integer, string, array, etc). :D

<img width="660" alt="Screen Shot 2022-06-27 at 1 32 55 PM" src="https://user-images.githubusercontent.com/72356175/176001172-9fa2629b-b02c-4c93-a932-c05fd0956b88.png">

2022-06-27 17:38 UTC, bbqxaxiu commented on src/components/CompaniesFilter.tsx
> +            options={CompanyFilters.SECTORS}
hi Sohee, how do you suggest doing that, given what I said in my response about how no prop allows us to manually change the value of the label?

2022-06-27 17:49 UTC, limsohee1002 commented on src/components/CompaniesFilter.tsx
> +            options={CompanyFilters.SECTORS}
It seems like it is not supported. hm is there any reason that you pick that specific dropdown?

2022-06-27 17:51 UTC, limsohee1002 commented on src/components/layouts/InvestmentsList.tsx
> +        })}
If you are using `{}` you should return the element?

2022-06-27 17:58 UTC, bbqxaxiu commented on src/components/CompaniesFilter.tsx
> +            options={CompanyFilters.SECTORS}
given our time constraints (we only have ~2 dev days to work on this), I liked that this dropdown was simple and allowed us to easily modify its appearance (via class selectors that it exposes in its readme) and to choose what symbol we use for the dropdown arrows (which was an important part of our design)

2022-06-27 18:20 UTC, limsohee1002 commented
Hey @bbqxaxiu I was looking into dropdown issue and found bug
https://www.loom.com/share/94ccc8430c73458c86d71f2daea7edf6
when you see, after you click clear all button, when you activate the dropdown, the previously selected dropdown has selected state (which has "-" in front of label).

2022-06-27 20:00 UTC, mokaymokay commented on src/components/icons/DownCaret.tsx
> +    <div className={cx('DownCaret', className)}>
should still work if you put the classname on the svg directly?

2022-06-27 20:18 UTC, mokaymokay commented on src/lib/cms/types.ts
> +    companyType: t.string,
ooh.. i'm not too familiar with io-ts but i was able to find this. it should work if you do something like this: https://github.com/gcanti/io-ts/issues/216#issuecomment-461275424 if not, there are several other examples of how to use enum with io-ts

2022-06-27 20:48 UTC, mokaymokay commented on src/views/companies.tsx
> +  filterItems(investmentsList.items, prevFundCompanies);
we should set `currentFundCompanies` and `prevFundCompanies` in state, and use a `useEffect` hook to update those when `companyType` or `industryType` changes. it is basically what you're already doing, but using the react hooks will make the updates more efficient. also when i mentioned filter previously, i was referring to the `Array.filter` method. something like this should work:

```
useEffect(() => {
  const filteredCurrentFundCompanies =  
    portfolioListing.companies.filter(company => (item.companyType === companyType || companyType === CompanyType.ALL_COMPANIES) || (item.sector === industryType || industryType === CompanySector.ALL_SECTORS));
    
    setCurrentFundCompanies(filteredCurrentFundCompanies)
}, [companyType, industryType])
```

you should be able to do this for `prevFundCompanies` too with the same filtering logic

2022-06-27 20:49 UTC, limsohee1002 approved these changes

2022-06-27 21:04 UTC, mokaymokay commented on src/components/CompaniesFilter.tsx
> +    </div>
two things here:

1. we probably don't want to render the clear-filter-container div if we're not showing the clear button.

2. i would recommend creating a `handleClear` function outside of `renderClearFilterButton`. right now, every time `renderClearFilterButton` is called, it creates an anonymous function. it's more efficient if you just refer to a previously declared function.

i'd recommend the following:

```
const handleClear = () => {
   setCompanyType(CompanyType.ALL_COMPANIES);
   setIndustryType(CompanySector.ALL_SECTORS);
}

const ClearFilterButton = (
      <div className="CompaniesFilter__clear-filter-container">
        <button
          className="CompaniesFilter__clear-filter-button text-inline-subheader"
          onClick={handleClear}
        >
          Clear Filters
        </button>
        </div>
      )

<>
{companyType !== CompanyType.ALL_COMPANIES || industryType !== CompanySector.ALL_SECTORS && ClearFilterButton}
</>
```

2022-06-27 21:09 UTC, mokaymokay commented on src/components/CompaniesFilter.tsx
> +  setCompanyType: any;
instead of any, i think we can do `() => void`?

2022-06-27 21:13 UTC, mokaymokay commented on src/components/CompaniesFilter.tsx
> +            arrowOpen={<DownCaret />}
this is kinda nitpicky but could improve performance too... i think we should be able to create `<DownCaret />` once then pass it in as arrowClosed and arrowOpen props for both `<Dropdown />` components, i.e.:

```
const DropdownIcon = <DownCaret />;

arrowClosed={DropdownIcon}
arrowOpen={DropdownIcon}
```

2022-06-27 21:14 UTC, mokaymokay commented
this is looking much better. i left some comments based on best practices! :)

2022-06-28 19:00 UTC, bbqxaxiu commented on src/components/CompaniesFilter.tsx
> +    </div>
hi kay, thank you for these tips! i took in your comments and remixed it a little bit. see my changes and lmk what u think :) 

see more here for my reasoning: https://www.loom.com/share/379b957585994beb86ff246d42988d71

2022-06-28 19:02 UTC, bbqxaxiu commented on src/components/CompaniesFilter.tsx
> +    </div>
part 2: https://www.loom.com/share/d0e460ed083d4d2ab64a8696cc6aec27

2022-06-29 11:31 UTC, mokaymokay commented on src/components/layouts/PortfolioListing.tsx
> +const PortfolioListing: React.FC<Props> = ({ heading, companies }) => {
looks like you can remove WithBreakpoints HOC from this component since you don't need it anymore

2022-06-29 11:33 UTC, mokaymokay commented on src/lib/cms/types.ts
> +    companyType: t.string,
any luck here?

2022-06-29 18:12 UTC, bbqxaxiu commented on src/lib/cms/types.ts
> +    companyType: t.string,
yep! responded to u on twist :D

2022-07-21 19:16 UTC, merged