[WIP] Add Text Module
sanctuarycomputer/bbgv pull request #56
Opened 2020-11-20 20:44 UTC by chrismekim

### Description

### Type(s) of changes

- [ ] Bug fix
- [ ] New feature
- [ ] Update to an existing feature

### Motivation for PR

### How Has This Been Tested?

### Applicable screenshots:

### Follow-up PR

2020-11-23 14:08 UTC, limsohee1002 commented
Need RB

2020-11-23 16:28 UTC, chrismekim commented
@limsohee1002 @mokaymokay rebased :)

2020-11-24 13:31 UTC, limsohee1002 approved these changes

2020-11-24 13:31 UTC, limsohee1002 commented on src/components/layouts/TextModule.tsx
> +          <span className={cx(`TextModule__subheading primary-sm pr3_75 vertical-align-middle`)}>
It doesn't seem to need `cx` and string interpolation

2020-11-24 16:15 UTC, mokaymokay requested changes

2020-11-24 16:15 UTC, mokaymokay commented on src/styles/components/TextModule.scss
> +    &--style-hover {
I think we can get rid of state in the text module if we do something like:
```
&__button {
  &:hover {
     &-line-icon {
       width: 2.25rem;
     }
  }
}

```

2020-11-24 16:27 UTC, chrismekim commented on src/styles/components/TextModule.scss
> +    &--style-hover {
Like we talked about, I'm adding a to-do to change this after my current PRs are merged so I can change it all at once 😃

2020-11-24 16:33 UTC, merged