[WIP] Add InvestmentsList
sanctuarycomputer/bbgv pull request #63
Opened 2020-11-30 17:35 UTC by chrismekim

### Description

- Adds InvestmentsList and sets up Companies page

### Type(s) of changes

- [x] New feature

### Motivation for PR
#32 

### How Has This Been Tested?

View at` /companies`

### Applicable screenshots:

![image](https://user-images.githubusercontent.com/43737723/100643774-1a592b00-3300-11eb-87fa-7d95ab0583b2.png)

### Follow-up PR

2020-12-01 13:53 UTC, limsohee1002 reviewed
This PR needs rebase as well :)

2020-12-01 13:53 UTC, limsohee1002 commented on src/components/layouts/InvestmentsList.tsx
> +    <div className={cx(`InvestmentsList col-12 flex flex-row flex-wrap`, className)}>
You don't need ` here :)

2020-12-01 13:53 UTC, limsohee1002 commented on src/components/layouts/InvestmentsList.tsx
> +        <div key="" className="InvestmentsList__item col-12">
key is empty?

2020-12-01 13:53 UTC, limsohee1002 commented on src/components/layouts/InvestmentsList.tsx
> +              onMouseLeave={() => setHoverButton(false)}
I think you can do this with only css?
set it so that when the button hovered, grab the line icon and span inside. :)

2020-12-01 16:24 UTC, mokaymokay requested changes

2020-12-01 16:24 UTC, mokaymokay commented on src/components/layouts/InvestmentsList.tsx
> +              onMouseLeave={() => setHoverButton(false)}
yeah i think should just remove state now rather than later

2020-12-01 18:11 UTC, chrismekim commented on src/components/layouts/InvestmentsList.tsx
> +              onMouseLeave={() => setHoverButton(false)}
I ended up making a reusable component for this `LineIconWithButton` without state :) It still has a flickering issue but will work on that during QA!

2020-12-01 18:12 UTC, chrismekim commented on src/components/layouts/InvestmentsList.tsx
> +              onMouseLeave={() => setHoverButton(false)}
P.S. More files changed because I added `LineIconWithButton` to the other components using it.

2020-12-01 18:14 UTC, mokaymokay approved these changes

2020-12-02 14:06 UTC, limsohee1002 approved these changes

2020-12-02 14:06 UTC, merged