[WIP] Add FeaturedFoundersCarousel
sanctuarycomputer/bbgv pull request #70
Opened 2020-12-10 22:21 UTC by chrismekim

### Description

- Adds FeaturedFoundersCarousel to home

### Type(s) of changes

- [x] New feature

### Motivation for PR

### How Has This Been Tested?

- View at `/`
### Applicable screenshots:

![image](https://user-images.githubusercontent.com/43737723/101836796-abe84a00-3b03-11eb-9e9f-b60a386c3c01.png)

![image](https://user-images.githubusercontent.com/43737723/101836761-9a06a700-3b03-11eb-985d-c780b2e24abb.png)

### Follow-up PR

2020-12-10 22:22 UTC, chrismekim commented on src/App.tsx
> +          <MenuOverlay globalSettings={globalSettings} closeMenu={closeMenu} isOpen={menuIsOpen} />
When you click on a link the menu should close.

2020-12-10 22:23 UTC, chrismekim commented on src/components/layouts/HomeHero.tsx
> +                  className="HomeHero__founder primary-xxl bg-color-transparent inline text-decoration-none hover-color-lilac color-charcoal transition"
Button was not getting the correct font.

2020-12-10 22:23 UTC, chrismekim commented on src/lib/cms/groq/FeaturedFoundersCarousel.ts
> +    'vimeoId': vimeoId,
Has 3 images because in QA we may add a transition to each image.

2020-12-10 22:36 UTC, chrismekim commented
@mokaymokay Two things! It looks a bit different from the designs because I couldn't get it exact, so I am going to see if XXIX will be okay with it. And secondly, I'm having trouble making the view next pagination buttons work correctly. :( It's from the Cocoon slider. Maybe we can pair on this next week?

2020-12-11 18:14 UTC, mokaymokay requested changes

2020-12-11 18:14 UTC, mokaymokay commented on src/components/layouts/FeaturedFoundersCarousel.tsx
> +                onClick={() => this.next()}
this can be simplified to `onClick={this.next}`, whenever possible we want to limit creating anonymous functions inside the return, since every time the component re-renders, it creates a new function

2020-12-11 18:14 UTC, mokaymokay commented
> @mokaymokay Two things! It looks a bit different from the designs because I couldn't get it exact, so I am going to see if XXIX will be okay with it. And secondly, I'm having trouble making the view next pagination buttons work correctly. :( It's from the Cocoon slider. Maybe we can pair on this next week?

yeah sure, can help look at it!

2020-12-11 19:47 UTC, chrismekim commented on src/lib/cms/groq/FeaturedFoundersCarousel.ts
> +    'vimeoId': vimeoId,
Changing to an array!

2020-12-11 19:50 UTC, chrismekim commented on src/components/layouts/FeaturedFoundersCarousel.tsx
> +                onClick={() => this.next()}
Ahh yes I always get mixed up on this concept! THanks!

2020-12-14 15:41 UTC, mokaymokay approved these changes
General comment: I see that `generateFullName()` is used in many different places. Might be a good idea to add full name as an attribute to the founder object when we sanitize

2020-12-14 16:03 UTC, merged

2020-12-14 16:05 UTC, chrismekim commented
> General comment: I see that `generateFullName()` is used in many different places. Might be a good idea to add full name as an attribute to the founder object when we sanitize

That is a great idea!! I'm actually not sanitizing the founder object because I'm using `io-ts` like in Cocoon. I'm only sanitizing things that come in through the Portable Text serializer... is there another time/place where we would be able to sanitize the founder object?