Bugfix/carousel 2
sanctuarycomputer/bbgv pull request #93
Opened 2021-02-11 00:13 UTC by chrismekim

### Description

### Type(s) of changes

- [ ] Bug fix
- [ ] New feature
- [ ] Update to an existing feature

### Motivation for PR

### How Has This Been Tested?

### Applicable screenshots:

### Follow-up PR

2021-02-12 00:34 UTC, chrismekim commented
@limsohee1002 @mokaymokay FYI there will probably be styling adjustments after I get feedback in QA!

2021-02-12 21:06 UTC, mokaymokay requested changes
doesn't seem like the video plays when you click play, might need to add an autoplay?

2021-02-12 21:06 UTC, mokaymokay commented on src/components/base/Video.tsx
> -    this.setState({ player });
why remove this? maybe remove it from state then?

2021-02-12 21:06 UTC, mokaymokay commented on src/components/layouts/FoundersImpactSlideshow.tsx
> +            className="FoundersImpactSlideshow__right-tile bg-color-lilac-darker h100 w100 text-left radius-xs flex flex-col mb6md:mb0"
typo

2021-02-15 17:07 UTC, chrismekim commented on src/components/base/Video.tsx
> -    this.setState({ player });
oops, accidental removal! thanks!

2021-02-15 18:00 UTC, mokaymokay approved these changes

2021-02-15 19:55 UTC, limsohee1002 approved these changes

2021-02-15 19:56 UTC, merged